### PR TITLE
Lower DP threshold for chrX variants in males

### LINKED ISSUE #147: DP threshold for chrX for males
Similar to dropping the GQ threshold for chrX variants in males, do you think there should also be a lower AD threshold?

Related to https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/issues/127#issuecomment-1320413341

### PR DESCRIPTION
**Pull request by williamrowell**
Same justification as lowering the GQ threshold.  Closes #147

### CODE REVIEW

**Comment by brentp** [comment]
Are you sure about using 3? This means that 1 of 8 variants would appear hom_ref in a het sample if all depths were exactly 3.

**Comment by williamrowell** [comment]
You are right, 3 does seem too low, but I'm not sure I follow about variants appearing hom_ref.  For chrX variants in males outside of PAR, a few reads should be enough to indicate a variant is high quality.

**Comment by brentp** [comment]
Ah, right. Can you test on a few samples and verify the number of variants doesn't balloon? I'm hesitant to lower the threshold so far. Since most sequencing will be 30X illumina, this might be suprising.

**Comment by williamrowell** [comment]
I will, but I'll have to put it on the back burner for a bit.

**Comment by brentp** [comment]
No worries.
how about defaulting it to 6?
Then you can set `config.min_male_X_dp = 3` once in a file that you send to `--js`.

**Pull request merged**
